apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mainsecret.nonSensitive.servicename }}
  namespace: {{ .Values.mainsecret.nonSensitive.namespace }}
  labels:
    app: {{ .Values.mainsecret.nonSensitive.servicename }}
spec:
  selector:
    app: {{ .Values.mainsecret.nonSensitive.appname }}
  ports:
  {{- toYaml .Values.svc.ports | nindent 2 }}